book-app/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :reviews
  get 'pages/info'

  root to: redirect('/books')
  resources :books
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

book-app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

book-app/app/models/book.rb
class Book < ApplicationRecord
    has_many :reviews
end

book-app/app/models/review.rb
class Review < ApplicationRecord
    belongs_to :book
end

book-app/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

book-app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
  	before_action :authenticate_user!

  	before_action :configure_permitted_parameters, if: :devise_controller?

    protected

        def configure_permitted_parameters
            devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:firstname, :lastname, :email, :password) }
            devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:firstname, :lastname, :email, :password, :current_password) }
            
        end	
end

book-app/app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @reviews = @book.reviews.all  
    @review = @book.reviews.build
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :author, :description)
    end
end

book-app/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def info
  end
end

book-app/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)

    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:title, :rate, :description, :book_id)
    end
end

book-app/app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :set_user, only: [:show, :edit, :update] # probably want to keep using this
  
    # GET /users
    # GET /users.json
    def index
      @users = User.all
    end
  
    # # GET /users/1
    # # GET /users/1.json
    def show
  
    end
  
    # GET /users/1/edit
    def edit
  
    end
  
    # # PATCH/PUT /users/1
    # # PATCH/PUT /users/1.json
    def update
      respond_to do |format|
        if @user.update(user_params)
          format.html { redirect_to @user, notice: 'User was successfully updated.' }
          format.json { render :show, status: :ok, location: @user }
        else
          format.html { render :edit }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end
  
    private
      # Use callbacks to share common setup or constraints between actions.
      def set_user
        @user = User.find(params[:id])
      end
  
      # Never trust parameters from the scary internet, only allow the white list through.
      def user_params
        params.require(:user).permit(:role, :user_name)
      end
  
  end

book-app/app/helpers/application_helper.rb
module ApplicationHelper
end

book-app/app/helpers/books_helper.rb
module BooksHelper
end

book-app/app/helpers/pages_helper.rb
module PagesHelper
end

book-app/app/helpers/reviews_helper.rb
module ReviewsHelper
end

book-app/app/helpers/users_helper.rb
module UsersHelper
end

book-app/app/views/books/_form.html.erb
<div class="card-body">
  
  <%= form_with(model: book, local: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-group">
    <%= form.text_field :title , class: "input--style-3",placeholder:"Title"%>
  </div>

  <div class="input-group">
    
    <%= form.text_field :author , class: "input--style-3",placeholder:"Author" %>
  </div>

  <div class="input-group">
    
    <%= form.text_field :description , class: "input--style-3",placeholder:"Description" %>
  </div>

    <div class="actions">
      <%= form.submit%>
      
    </div>
    
  <% end %>

</div>

book-app/app/views/books/edit.html.erb
<div class="page-book">
<h2 class="text-book center-text">Edit Book</h2>
    <div class="card card-7">

        <%= render 'form', book: @book %>
        <div class="link"> 
        <%= link_to 'Show', @book ,class:"btn btn--pill btn--edit"%> |
        <%= link_to 'Back', books_path ,class:"btn btn--pill btn--edit"%></div>
       
    </div>
</div>

book-app/app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <h1 class="bottom">Books List</h1>
  <%= link_to 'New Book', new_book_path,class:"btn btn--pill btn--green bottom" %>
  <table class="table">
    <thead>
      <tr class="center-text ">
        <th>Title</th>
        <th>Author</th>
        <th>Description</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @books.each do |book| %>
        <tr class="center-text border-bottom">
          <td class="border-right"><%= book.title %></td>
          <td class="border-right"><%= book.author %></td>
          <td class="border-right"><%= book.description %></td>
          <td><%= link_to 'Update', edit_book_path(book),class:"btn btn--pill btn--blue" %></td>
          <td><%= link_to 'Delete', book,class:"btn btn--pill btn--red", method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

book-app/app/views/books/new.html.erb
<div class="page-book">
<h2 class="text-book center-text">New Book</h2>
    <div class="card card-4">

        <%= render 'form', book: @book %>
        <div class="link"> <%= link_to 'Back', books_path ,class:"btn btn--pill btn--back" %></div>
       
    </div>
</div>

book-app/app/views/books/show.html.erb
<div class="card card-6">
  <div class="card-table">
    <p>
      <strong>Title:</strong>
      <%= @book.title %>
    </p>

    <p>
      <strong>Author:</strong>
      <%= @book.author %>
    </p>

    <p>
      <strong>Description:</strong>
      <%= @book.description %>
    </p>

    <p>
      <h3>Reviews</h3>
      <% @reviews.each do |review| %>
        <div>
          <strong>Title:<%= review.title %></strong>
          <br>
          <strong>Rate:<%= review.rate %></strong>
          <br>
          <strong>Description:<%= review.description %></strong>
          <br>
          <p>Book-id:<%= review.book_id %></p>
          <p><%= link_to 'Delete', review_path(review),class:"btn btn--pill btn--red", method: :delete, data: { confirm: 'Are you sure?' } %></p>
        </div>
      <% end %>
    </p>
  </div>

  <div class="card-bodies">
      <div class="page-book">
        <h2 class="text-book center-text">New Review</h2>
            <div class="card-8 card-5">
                <%= render partial: 'reviews/form', locals: { review: @review } %>

                <div class="node"> 
                  <%= link_to 'Edit', edit_book_path(@book) ,class:"btn btn--pill btn--node"%> |
                  <%= link_to 'Back', books_path ,class:"btn btn--pill btn--node"%></div>
            </div>
        </div>
  </div>
</div>

book-app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="">

    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <div class="container">
        <a class="navbar-brand" href="/">The Idea App</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="/books">Book List</a>
            </li>
            <li class="nav-item">
              <%= link_to 'New Book', new_book_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/pages/info">Info</a>
            </li>
          </ul>
          <p class="navbar-text float-right">
              <% if user_signed_in? %>
                Logged in as <strong><%= current_user.firstname %><%= current_user.lastname %></strong>.
                <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
                <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
              <% else %>
                <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
                <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
              <% end %>
          </p>
        </div>
      </div>
    </nav>

    <div class="fix-container ">
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
      <%= yield %>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
  </body>
</html>

book-app/app/views/pages/info.html.erb
<h1>Pages#info</h1>
<p>Find me in app/views/pages/info.html.erb</p>

book-app/app/views/reviews/_form.html.erb
<div class="card-bodiess">
  
  <%= form_with(model: review, local: true) do |form| %>
  <% if review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
        <% review.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-group">
    <%= form.text_field :title , class: "input--style-3",placeholder:"Title"%>
  </div>

  <div class="input-group">
    
    <%= form.number_field :rate, min: 1, max: 5 , class: "input--style-3",placeholder:"Rate" %>
  </div>

  <div class="input-group">
    
    <%= form.text_field :description , class: "input--style-3",placeholder:"Description" %>
  </div>


  
    <%= form.hidden_field :book_id , class: "input--style-3",placeholder:"Description" %>


    <div class="actions">
      <%= form.submit%>
      
    </div>
    
  <% end %>

</div>

book-app/app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

book-app/app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reviews</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Rate</th>
      <th>Description</th>
      <th>Book</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.title %></td>
        <td><%= review.rate %></td>
        <td><%= review.description %></td>
        <td><%= review.book_id %></td>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

book-app/app/views/reviews/new.html.erb
<div class="page-book">
<h2 class="text-book center-text">New Review</h2>
    <div class="card card-4">

        <%= render 'form', review: @review %>
        <div class="link"> <%= link_to 'Back',reviews_path ,class:"btn btn--pill btn--back" %></div>
       
    </div>
</div>

book-app/app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @review.title %>
</p>

<p>
  <strong>Rate:</strong>
  <%= @review.rate %>
</p>

<p>
  <strong>Description:</strong>
  <%= @review.description %>
</p>

<p>
  <strong>Book:</strong>
  <%= @review.book_id %>
</p>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>

book-app/app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

book-app/app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>